Improved scripts.

diff --git a/src/pbuilder/pbuilderrc b/src/pbuilder/pbuilderrc
--- a/src/pbuilder/pbuilderrc
+++ b/src/pbuilder/pbuilderrc
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
 # NorNet Core pbuilderrc File
 # Copyright (C) 2012-2021 by Thomas Dreibholz
 #
@@ -17,6 +18,7 @@
 #
 # Contact: dreibh@simula.no
 
+# Bash options:
 set -e
 
 
@@ -29,7 +31,7 @@ if [ "${DIST}" == "" ] ; then
    DIST=`lsb_release -cs`
 fi
 if [ "${ARCH}" == "" ] ; then
-   ARCH=`uname -m`
+   ARCH=`dpkg --print-architecture`
 fi
 
 
@@ -38,19 +40,29 @@ DISTRIBUTION="${DIST}"
 COMPONENTS="main universe"
 if [ "${OS}" == "ubuntu" ] ; then
    MIRRORSITE=http://no.archive.ubuntu.com/ubuntu/
-   DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--keyring=/usr/share/keyrings/ubuntu-archive-keyring.gpg")
+   KEYRING="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
 elif [ "${OS}" == "debian" ] ; then
-   if [ "${ARCH}" == "m68k" ] ; then
+   if [ "${ARCH}" == "m68k" -o  "${ARCH}" == "riscv64" ] ; then
       # M68k port for Amiga, etc.:
       MIRRORSITE="http://ftp.ports.debian.org/debian-ports/"
-      DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--keyring=/usr/share/keyrings/debian-ports-keyring.gpg")      
+      KEYRING="/usr/share/keyrings/debian-ports-archive-keyring.gpg"
    else
       MIRRORSITE="http://ftp.no.debian.org/debian/"
-      DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg")
+      KEYRING="/usr/share/keyrings/debian-archive-keyring.gpg"
    fi
+else
+   echo >&2 "ERROR: Unknown Linux distribution ${OS}!"
+   exit 1
 fi
+if [ ! -e "${KEYRING}" ] ; then
+   echo >&2 "ERROR: Missing keyring file ${KEYRING}!"
+   exit 1
+fi
+DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--keyring=${KEYRING}")
+DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--variant=buildd")
 ARCHITECTURE="${ARCH}"
-# DEBOOTSTRAPOPTS=("${DEBOOTSTRAPOPTS[@]}" "--arch=$ARCH")
+
+COMPRESSPROG=pigz
 EXTRAPACKAGES=eatmydata
 EATMYDATA=yes
 
@@ -61,8 +73,8 @@ export DEB_BUILD_OPTIONS="parallel=${cores}"
 # Support tmpfs build
 # (see http://www.davromaniak.eu/index.php?post/2011/07/12/Pbuilder-and-tmpfs-can-be-friends)
 # Add to /etc/fstab:
-# tmpfs   /var/cache/pbuilder/build   tmpfs   defaults,auto   0	2
-
+# tmpfs   /var/cache/pbuilder/build   tmpfs   defaults,auto   0   2
+#
 APTCACHEHARDLINK=no
 
 
@@ -74,16 +86,12 @@ BUILDPLACE="/var/cache/pbuilder/build/"
 BUILDRESULT="/var/cache/pbuilder/${NAME}/result/"
 HOOKDIR="/var/cache/pbuilder/hook.d/"
 
-echo "X-1"
-mkdir -p {$APTCACHE}
+mkdir -p ${APTCACHE}
 mkdir -p ${BUILDRESULT}
 mkdir -p ${HOOKDIR}
-echo "X-2"
-ls -R /var/cache/pbuilder/${NAME}/
 
 
 # ====== Debugging hook =====================================================
-
 cat >${HOOKDIR}/C10shell <<EOF
 #!/bin/sh
 # Run when the build fails:
