Check IP address for new configuration.

diff --git a/src/scripts/Configure-iLO b/src/scripts/Configure-iLO
--- a/src/scripts/Configure-iLO
+++ b/src/scripts/Configure-iLO
@@ -65,7 +65,7 @@ NODE_FQDN=`hostname --fqdn`
 NODE_HOSTNAME=`echo "$NODE_FQDN" | sed -e "s/^\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.\-]*\)$/ilo-\1/g"`
 NODE_DOMAINNAME=`echo "$NODE_FQDN" | sed -e "s/^\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.\-]*\)$/\2/g"`
 
-NODE_ADDRESS=`host "$NODE_HOSTNAME" | awk '/^[a-zA-Z0-9.-]+ has address/ { print $4 }'`
+NODE_ADDRESS=`host "$NODE_HOSTNAME.$NODE_DOMAINNAME" | awk '/^[a-zA-Z0-9.-]+ has address/ { print $4 }'`
 NODE_NETMASK="255.255.255.0"
 NODE_TUNNELBOX=`echo "$NODE_ADDRESS" | sed -e 's/^\([0-9]*\.[0-9]*\.[0-9]*\)\.[0-9]*$/\1.1/g'`
 
@@ -76,6 +76,11 @@ echo "NODE_ADDRESS=$NODE_ADDRESS"
 echo "NODE_NETMASK=$NODE_NETMASK"
 echo "NODE_TUNNELBOX=$NODE_TUNNELBOX"
 echo -en "\x1b[0m"
+
+if [ "$NODE_ADDRESS" = "" ] ; then
+   echo 2>&1 "ERROR: Unable to determine IP address of $NODE_FQDN! Is DNS properly configured?"
+   exit 1
+fi
 
 
 # ====== Obtain old iLO configuration and generate new one ==================
