Added comment.

diff --git a/src/scripts/convert-disk-images b/src/scripts/convert-disk-images
--- a/src/scripts/convert-disk-images
+++ b/src/scripts/convert-disk-images
@@ -4,5 +4,9 @@ FROM=img
 TO=vdi
 for i in 0 1 2 3 ; do
    echo "Converting DH$i from $FROM to $TO ..."
-   qemu-img convert -p DH$i.$FROM -O $TO DH$i.$TO
+   if [ ! -e DH$i.$TO ] ; then
+      qemu-img convert -p DH$i.$FROM -O $TO DH$i.$TO
+   else
+      echo >&2 "ERROR: DH$i.$TO already exists!"
+   fi
 done
