Updated helper scripts.

diff --git a/src/scripts/k2 b/src/scripts/k2
--- a/src/scripts/k2
+++ b/src/scripts/k2
@@ -21,7 +21,7 @@
 
 # ====== Repository cleaning ==============================
 git clean -x -d -f
-cp $HOME/kernel-config .config
+# cp $HOME/kernel-config .config
 
 
 # # ====== Fix PIE compile problem for GCC 6.x ============
@@ -31,9 +31,9 @@ cp $HOME/kernel-config .config
 # --- a/Makefile
 # +++ b/Makefile
 # @@ -611,6 +611,12 @@ include arch/\$(SRCARCH)/Makefile
-#  
+#
 #  KBUILD_CFLAGS  += \$(call cc-option,-fno-delete-null-pointer-checks,)
-#  
+#
 # +# force no-pie for distro compilers that enable pie by default
 # +KBUILD_CFLAGS += \$(call cc-option, -fno-pie)
 # +KBUILD_CFLAGS += \$(call cc-option, -no-pie)
@@ -44,50 +44,38 @@ cp $HOME/kernel-config .config
 #  KBUILD_CFLAGS  += -Os \$(call cc-disable-warning,maybe-uninitialized,)
 #  else
 # EOF
-# 
+#
 # git checkout Makefile
 # patch -p1 <Makefile.patch
 
 
-# ====== Version check ====================================
-echo "Kernel Version  `make kernelversion`"
-echo "Kernel Release: `make kernelrelease`"
-if [ "`make kernelrelease`" != "`make kernelversion`" ] ; then
-   echo >&2 "ERROR: Versioning issues - packaging will not work properly!"
-   exit 1
-fi
+# # ====== Version check ====================================
+# echo "Kernel Version  `make kernelversion`"
+# echo "Kernel Release: `make kernelrelease`"
+# if [ "`make kernelrelease`" != "`make kernelversion`" ] ; then
+#    echo >&2 "ERROR: Versioning issues - packaging will not work properly!"
+#    exit 1
+# fi
 
 
-# ====== "Kernel Package" =================================
-# Using the Git version here.
-# NOTE: kernel-package/kernel (sub-directory!) corresponds to
-#       /usr/share/kernel-package
-if [ ! -e $HOME/src/kernel-package -o ! -e $HOME/src/kernel-package/kernel ] ; then
-   echo >&2 "ERROR: $HOME/src/kernel-package or $HOME/src/kernel-package/kernel does not exist!"
-   echo >&2 "Use: git clone https://github.com/dreibh/kernel-package.git $HOME/src/kernel-package"
-   exit 1
-fi
+cp -r ~/src/ubuntu-trusty/debian .
+cp -r ~/src/ubuntu-trusty/debian.master .
 
+# cp .config debian.master/config/config.common.ubuntu
+cp $HOME/kernel-config debian.master/config/config.common.ubuntu
 
-# ====== Clean ============================================
-$HOME/src/kernel-package/make-kpkg --rootcmd fakeroot \
-   --overlay-dir $HOME/src/kernel-package/kernel \
-   clean
+cat >debian.master/changelog <<EOF
+linux (4.1.31-mptcp) xenial; urgency=low
 
-# ====== Create source package ============================
-$HOME/src/kernel-package/make-kpkg --rootcmd fakeroot \
-   --overlay-dir $HOME/src/kernel-package/kernel \
-   --stem linux \
-   --initrd  \
-   --revision 15 \
-   debian
+  * This is a dummy changelog for packages generated by kernel-package. At
+    some point, there shall be hooks for the user to substitute a
+    changelog entry, but currently this is just a stub.
 
-#    --append-to-version "-custom" \
-
-
-echo 'Building Package' >stamp-building
+ -- Thomas Dreibholz <dreibh@simula.no>  Wed, 29 Jun 2016 08:08:08 +0800
+EOF
 
 export MAINTAINER="Thomas Dreibholz <dreibh@iem.uni-due.de>"
-dpkg-buildpackage -S -sa -k"${MAINTAINER}" -rfakeroot -I.git -I.gitignore -i'\.git.*'
 
-rm -f stamp-building
+fakeroot debian/rules insertchanges
+fakeroot debian/rules clean
+dpkg-buildpackage -S -sa -k"${MAINTAINER}" -rfakeroot -I.git -I.gitignore -i'\.git.*'
