Some improvements.

diff --git a/src/SSH/make-tbox-scripts b/src/SSH/make-tbox-scripts
--- a/src/SSH/make-tbox-scripts
+++ b/src/SSH/make-tbox-scripts
@@ -1,30 +1,40 @@
 #!/bin/bash
 
-SITES="10.1.1.1 10.1.2.1 10.1.3.1 10.1.4.1 10.1.5.1 10.1.6.1 10.1.7.1 10.1.8.1 10.1.9.1 10.1.10.1 10.1.11.1 10.20.30.1 10.30.40.1 10.30.41.1 10.30.42.1 10.80.88.1 10.90.100.1 10.70.160.1 10.150.200.1 10.30.43.1 10.82.89.1"
+rm -f tbox* tbext* cbox*
 
-rm -f tbox*
+../Get-Control-IPs >control.list
 
-i=1
-for site in $SITES ; do
-   name=`printf "tbox%02d" $i`
-   ( echo "#!/bin/sh"
-     echo "echo \"Connecting to $site ...\""
-     echo "ssh -C nornetpp@$site" ) >$name
-   chmod +x $name
-   let i=$i+1
-done
+(
+   while read number index tbint tbext cbext name ; do
+      siteName=`echo "$name" | tr -d '"'`
+      # echo "n=$number $tbint - $tbext   N=$siteName."
 
+      for type in tbox tbext cbox ; do
+         if [ "$type" == "tbox" -o "$type" == "tbext" ] ; then
+            if [ "$type" == "tbext" ] ; then
+               ip="$tbext"
+            else
+               ip="$tbint"
+            fi
+            typeName="Tunnelbox"
+         else
+            ip="$cbext"
+            typeName="Control Box"
+            if [ "$ip" == "0.0.0.0" ] ; then
+               echo >&2 "ERROR: No control box address! Needs to access PLC as admin"
+               continue
+            fi
+         fi
 
-CONTROLBOX="158.39.4.3 129.240.66.75 128.39.49.165 129.242.157.229 152.94.120.7 158.37.6.194 158.36.50.179 158.39.149.133 129.241.200.129 158.39.93.232 128.39.120.63 131.246.112.121 141.22.27.236 132.252.152.73 193.10.227.86 210.37.45.148 164.113.202.19 203.230.60.126 221.199.217.168 130.83.162.211 202.100.206.164"
-i=1
-for controlBox in $CONTROLBOX ; do
-   name=`printf "cbox%02d" $i`
-   ( echo "#!/bin/sh"
-     echo "echo \"Connecting to $controlBox ...\""
-     echo "ssh -C nornetpp@$controlBox" ) >$name
-   chmod +x $name
-   let i=$i+1
-done
+         outputFile=`printf "$type%02d" $number`
+         ( echo "#!/bin/sh"
+           echo "echo \"Connecting to $typeName of $siteName ($ip) ...\""
+           echo "ssh -C nornetpp@$ip" ) >$outputFile
+         chmod +x $outputFile
+      done
+   done
+) <control.list
+
 
 ILOGATEWAY="158.39.4.3:10.1.1.244 129.240.66.75:10.1.2.244 128.39.49.165:10.1.3.244 129.242.157.229:4002:10.1.4.244 152.94.120.7:10.1.5.244 158.37.6.194:10.1.6.244 158.36.50.182:10.1.7.244 158.39.149.133:10.1.8.244 129.241.200.129:10.1.9.244 158.39.93.232:10.1.10.244"
 i=1
