Improved script.

diff --git a/src/system-info.d/10-nornet b/src/system-info.d/10-nornet
--- a/src/system-info.d/10-nornet
+++ b/src/system-info.d/10-nornet
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
-# Print system information
-# Copyright (C) 2013-2024 by Thomas Dreibholz
+# NorNet System-Info system-info.d Script
+# Copyright (C) 2013-2025 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,59 +16,26 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Contact: dreibh@simula.no
+# Contact: thomas.dreibholz@gmail.com
 
+# Bash options:
+set -eu
 
-# Get the width of the terminal. Assume 80, if unknown.
-if [ "${TERM}" != "dumb" ] ; then
-   TERMINAL_WIDTH=`tput cols`
-else
-   TERMINAL_WIDTH=80
-fi
-
-
-# ###### Center text in console #############################################
-center ()
-{
-   local text="$1"
-   local length=${#text}
-   local width=${TERMINAL_WIDTH}
-
-   let indent=(${width} - ${length})/2
-   if [ ${indent} -lt 0 ] ; then
-      indent=0
-   fi
-   printf "%${indent}s%s\n" "" "${text}"
-}
-
-
-# ###### Print centered separator in console ################################
-separator ()
-{
-   local separatorCharacter="="
-   local separator=""
-   local width=${TERMINAL_WIDTH}
-   local separatorWidth
-
-   let separatorWidth=${width}-4
-   local i=0
-   while [ $i -lt ${separatorWidth} ] ; do
-      separator="${separator}${separatorCharacter}"
-      let i=$i+1
-   done
-   center "${separator}"
-}
+# Helper function library -> just return when it is not available.
+# Exit code 0 will let System-Info continue with the next script!
+# shellcheck disable=SC1091
+. "$(dirname "$0")/banner-helper" || exit 0
 
 
 # ====== Print banner =======================================================
 
 NORNET_VERSION=""
 if [ -e /etc/nornet/nornet-version ] ; then
-   NORNET_VERSION=`cat /etc/nornet/nornet-version`
+   NORNET_VERSION="$(cat /etc/nornet/nornet-version)"
 fi
 
 echo -en "\x1b[1;34m"
-separator
+separator "  " "=" "  "
 echo -en "\x1b[1;31m"
 center "#     #                 #     #                "
 center "##    #   ####   #####  ##    #  ######   #####"
@@ -82,7 +49,7 @@ if [ "${NORNET_VERSION}" != "" ] ; then
    echo ""
    center "${NORNET_VERSION}"
 fi
-separator
+separator "  " "=" "  "
 echo -e "\x1b[0m"
 
 
