Tunnelbox configuration fix for Ubuntu Xenial.

diff --git a/debian/nornet-tunnelbox.init b/debian/nornet-tunnelbox.init
--- a/debian/nornet-tunnelbox.init
+++ b/debian/nornet-tunnelbox.init
@@ -198,7 +198,13 @@ check_and_configure ()
       if needs_update squid-config /etc/squid3/squid.conf $1 ; then
          echo -e "\x1b[33m`env LANG=C date +%FT%H:%M:%S`: Squid server configuration has been updated => restarting Squid service ...\x1b[0m"
          cp squid-config /etc/squid3/squid.conf
-         service squid3 restart >/dev/null || true
+         if [ -e /etc/init.d/squid ] ; then
+            service squid restart >/dev/null || true
+         elif [ -e /etc/init.d/squid3 ] ; then
+            service squid3 restart >/dev/null || true
+         else
+            echo "ERROR: How is the name of the Squid service?"
+         fi
       fi
 
       # ====== Apply registrar configuration update =========================
