Updated scripts to handle firewall rules also for Node, not only for Tunnelbox.

diff --git a/debian/nornet-node.init b/debian/nornet-node.init
--- a/debian/nornet-node.init
+++ b/debian/nornet-node.init
@@ -150,6 +150,32 @@ get_new_node_configuration ()
    done
 
    cd ..
+
+   # ====== Apply firewall update ===========================================
+   rm -f firewall4-config firewall6-config
+   mv updated-tunnelbox-config/firewall4-config .
+   mv updated-tunnelbox-config/firewall6-config .
+   needsFirewallUpdate=0
+   if needs_update firewall4-config /etc/iptables/rules.v4 $1 ; then
+      cp firewall4-config /etc/iptables/rules.v4
+      needsFirewallUpdate=1
+   fi
+   if needs_update firewall6-config /etc/iptables/rules.v6 $1 ; then
+      cp firewall6-config /etc/iptables/rules.v6
+      needsFirewallUpdate=1
+   fi
+   if [ $needsFirewallUpdate -ne 0 ] ; then
+      echo -e "\x1b[33m`env LANG=C date +%FT%H:%M:%S`: Firewall configuration has been updated => restarting netfilter-persistent service ...\x1b[0m"
+      if [ -e /etc/init.d/netfilter-persistent ] ; then
+         service netfilter-persistent restart >/dev/null || true
+      elif [ -e /etc/init.d/iptables-persistent ] ; then
+         service iptables-persistent restart >/dev/null || true
+      else
+         echo "ERROR: What is the name of the netfilter-persistent service?"
+      fi
+   fi
+   
+   # ====== Update other configurations =====================================   
    mv updated-node-config/* .
    rmdir updated-node-config
 }
