Improved RPM packaging tool-chain.

diff --git a/src/fedora-build-toolchain/build-all b/src/fedora-build-toolchain/build-all
--- a/src/fedora-build-toolchain/build-all
+++ b/src/fedora-build-toolchain/build-all
@@ -1,13 +1,26 @@
 #!/bin/bash -e
 
 SOURCES="/nfs/pub/src"
-ALL_PACKAGES="subnetcalc"
+REPOSITORIES="/tmp/repos"
+DISTRIBUTIONS="fedora-18-x86_64 fedora-18-i386"
+# PACKAGES="bibtexconv fractgen2 netperfmeter rsplib2 subnetcalc"
+PACKAGES="netperfmeter"
 
-# ====== SubNetCalc =======================================
-subnetcalc_DIR="$SOURCES/misc-trunk/subnetcalc"
+
+# ====== BibTeXConv =======================================
+bibtexconv_DIR="$SOURCES/misc-trunk/bibtexconv"
+
+# ====== Fractal Generator ================================
+fractgen_DIR="$SOURCES/misc-trunk/fractgen2"
 
 # ====== NetPerfMeter =====================================
 netperfmeter_DIR="$SOURCES/misc-trunk/netperfmeter"
+
+# ====== rsplib ===========================================
+rsplib_DIR="$SOURCES/sctp-trunk/rsplib2"
+
+# ====== SubNetCalc =======================================
+subnetcalc_DIR="$SOURCES/misc-trunk/subnetcalc"
 
 
 
@@ -26,8 +39,18 @@ while [ "$1" != "" ] ; do
    shift
 done
 
+
+# ====== Prepare output directories =========================================
+echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Preparing repositories in $REPOSITORIES ...\x1b[0m"
+DISTRIBUTION_DIRECTORIES=`echo "$DISTRIBUTIONS" | sed -e "s/-/\//g"`
+echo "D=$DISTRIBUTION_DIRECTORIES"
+for directory in $DISTRIBUTION_DIRECTORIES ; do
+   mkdir -p "$REPOSITORIES/$directory"
+done
+
+
 # ====== Packaging loop =====================================================
-for package in $ALL_PACKAGES ; do
+for package in $PACKAGES ; do
    echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Packaging $package ...\x1b[0m"
    eval "package_dir=\$${package}_DIR"
    cd "$package_dir"
@@ -44,14 +67,30 @@ for package in $ALL_PACKAGES ; do
 
    # ====== Upstream sources ================================================
    eval "package_dir=\$${package}_DIR"
-   echo -e "\x1b[1;32m`date +%FT%H:%M:%S`: Creating upstream sources for $package ...\x1b[0m"
-   if [ -e "debian.conf" ] ; then
-      . ./debian.conf
-      $MAKE_DIST
-   else
-      echo "HOW TO GET UPSTREAM SOURCES?"
-      exit 1
-   fi
+   echo -e "\x1b[1;32m`date +%FT%H:%M:%S`: Creating RPMs for $package ...\x1b[0m"
+
+   ./make-rpm $DISTRIBUTIONS
+
+   for distribution in $DISTRIBUTIONS ; do
+      rpms=`find /var/lib/mock/$distribution/result -name "$package*.rpm" || true`
+      if [ "$rpms" == "" ] ; then
+         echo >&2 "ERROR: Cannot find RPMs for package $package in /var/lib/mock/$distribution/result!"
+         exit 1
+      fi
+      directory=`echo "$distribution" | sed -e "s/-/\//g"`
+      cp $rpms "$REPOSITORIES/$directory"
+   done
+
 done
+
+
+# ====== Update repository management files =================================
+echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Updating repositories ...\x1b[0m"
+for directory in $DISTRIBUTION_DIRECTORIES ; do
+   $(repomanage --keep=2 --old "$REPOSITORIES/$directory") | xargs --no-run-if-empty rm -f
+   createrepo "$REPOSITORIES/$directory" --update
+done
+tree $REPOSITORIES/
+
 
 echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Successfully completed package creation!\x1b[0m"
