Script update.

diff --git a/src/fedora-build-toolchain/build-nornet-applications-repository b/src/fedora-build-toolchain/build-nornet-applications-repository
--- a/src/fedora-build-toolchain/build-nornet-applications-repository
+++ b/src/fedora-build-toolchain/build-nornet-applications-repository
@@ -23,33 +23,39 @@
 HOME="/home/nornetpp"
 
 SOURCES="$HOME/src"
-REPOSITORIES="/home/nornetpp/repos/nornet-applications"
-DISTRIBUTIONS="fedora-18-x86_64 fedora-20-x86_64 fedora-21-x86_64   fedora-18-i386 fedora-20-i386 fedora-21-i386"
+REPOSITORIES="$HOME/repos/nornet-applications"
+DISTRIBUTIONS="fedora-18-x86_64 fedora-20-x86_64 fedora-21-x86_64 fedora-22-x86_64  fedora-18-i386 fedora-20-i386 fedora-21-i386 fedora-22-i386"
 
-PACKAGES="bibtexconv fractgen netperfmeter rsplib subnetcalc tsctp libvirt"
-#PACKAGES="fractgen"
+PACKAGES="bibtexconv fractgen netperfmeter rsplib subnetcalc tsctp"
+#PACKAGES="libvirt"
 
 
 # ====== BibTeXConv =======================================
-bibtexconv_DIR="$SOURCES/misc-trunk/bibtexconv"
+bibtexconv_DIR="bibtexconv"
+bibtexconv_REPO="git://github.com/dreibh/bibtexconv.git"
 
 # ====== Fractal Generator ================================
-fractgen_DIR="$SOURCES/misc-trunk/fractgen2"
+fractgen_DIR="fractgen"
+fractgen_REPO="git://github.com/dreibh/fractgen.git"
 
 # ====== NetPerfMeter =====================================
-netperfmeter_DIR="$SOURCES/misc-trunk/netperfmeter"
+netperfmeter_DIR="netperfmeter"
+netperfmeter_REPO="git://github.com/dreibh/netperfmeter.git"
 
 # ====== rsplib ===========================================
-rsplib_DIR="$SOURCES/sctp-trunk/rsplib2"
+rsplib_DIR="rsplib"
+rsplib_REPO="git://github.com/dreibh/rsplib.git"
 
 # ====== SubNetCalc =======================================
-subnetcalc_DIR="$SOURCES/misc-trunk/subnetcalc"
+subnetcalc_DIR="subnetcalc"
+subnetcalc_REPO="git://github.com/dreibh/subnetcalc.git"
 
 # ====== TSCTP ============================================
-tsctp_DIR="$SOURCES/misc-trunk/tsctp"
+tsctp_DIR="tsctp"
+tsctp_REPO="git://github.com/dreibh/tsctp.git"
 
 # ====== libvirt ==========================================
-libvirt_DIR="`pwd`/libvirt"
+# libvirt_DIR="`pwd`/libvirt"
 
 ## ====== Tracebox =========================================
 #tracebox_DIR="$SOURCES/tracebox"
@@ -73,17 +79,6 @@ libvirt_DIR="`pwd`/libvirt"
 
 # ====== Handle arguments ===================================================
 WORKDIR=`pwd`
-UPDATE=0
-while [ "$1" != "" ] ; do
-   if [ "$1" = "-update" ] ; then
-      UPDATE=1
-   else
-      echo >&2 "Usage: $0 [-update]"
-      exit 1
-   fi
-   shift
-done
-
 
 # ====== Prepare output directories =========================================
 echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Preparing repositories in $REPOSITORIES ...\x1b[0m"
@@ -103,43 +98,51 @@ for package in $PACKAGES ; do
       echo >&2 "ERROR: Invalid directory given in ${package}_DIR!"
       exit 1
    fi
-   cd "$package_dir"
+   rm -rf "$package_dir"
 
-   # ====== Update ==========================================================
-   if [ $UPDATE -eq 1 ] ; then
-      echo -e "\x1b[1;32m`date +%FT%H:%M:%S`: Updating package $package ...\x1b[0m"
-      if svn info >/dev/null 2>&1 ; then
-         svn update
-      else
-         git pull
-      fi
+
+   # ====== Clone ===========================================================
+   package_repo=""
+   eval "package_repo=\$${package}_REPO"
+   if [ "$package_repo" == "" ] ; then
+      echo >&2 "ERROR: Invalid repoectory given in ${package}_REPO!"
+      exit 1
    fi
+   rm -rf "$package_repo"
+   git clone "$package_repo" "$package_dir"
 
-   # ====== Upstream sources ================================================
-   eval "package_dir=\$${package}_DIR"
-   echo -e "\x1b[1;32m`date +%FT%H:%M:%S`: Creating RPMs for $package ...\x1b[0m"
 
-   ./clean-deb
-   ./make-rpm $DISTRIBUTIONS
+   # ====== Build ===========================================================
+   (
+      cd "$package_dir"
 
-   for distribution in $DISTRIBUTIONS ; do
-      rpms=`find /var/lib/mock/$distribution/result -name "$package*.rpm" || true`
-      if [ "$rpms" == "" ] ; then
-         echo >&2 "ERROR: Cannot find RPMs for package $package in /var/lib/mock/$distribution/result!"
-         exit 1
-      fi
-      directory=`echo "$distribution" | sed -e "s/-/\//g"`
-      for rpm in $rpms ; do
-         if [[ "$rpm" =~ \.src\.rpm$ ]] ; then
-            echo "S=$rpm"
-            cp "$rpm" "$REPOSITORIES/$directory/SRPMS/"
-         else
-            echo "B=$rpm"
-            cp "$rpm" "$REPOSITORIES/$directory/RPMS/"
+      # ====== Build SRPM ===================================================
+      eval "package_dir=\$${package}_DIR"
+      echo -e "\x1b[1;32m`date +%FT%H:%M:%S`: Creating RPMs for $package ...\x1b[0m"
+
+      ./clean-deb
+      ./make-rpm $DISTRIBUTIONS
+
+      # ====== Build RPMs ===================================================
+      for distribution in $DISTRIBUTIONS ; do
+         rpms=`find /var/lib/mock/$distribution/result -name "$package*.rpm" || true`
+         if [ "$rpms" == "" ] ; then
+            echo >&2 "ERROR: Cannot find RPMs for package $package in /var/lib/mock/$distribution/result!"
+            exit 1
          fi
+         directory=`echo "$distribution" | sed -e "s/-/\//g"`
+         for rpm in $rpms ; do
+            if [[ "$rpm" =~ \.src\.rpm$ ]] ; then
+               echo "S=$rpm"
+               cp "$rpm" "$REPOSITORIES/$directory/SRPMS/"
+            else
+               echo "B=$rpm"
+               cp "$rpm" "$REPOSITORIES/$directory/RPMS/"
+            fi
+         done
       done
-   done
 
+   )
 done
 
 cd "$WORKDIR"
@@ -153,7 +156,7 @@ cd "$WORKDIR"
 echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Updating repositories ...\x1b[0m"
 for directory in $DISTRIBUTION_DIRECTORIES ; do
    cp nornet-groups.xml "$REPOSITORIES/$directory"
-   
+
    oldPackages=`repomanage --keep=2 --old "$REPOSITORIES/$directory"`
    for oldPackage in $oldPackages ; do
       echo "Removing $oldPackage"
