Added dependency python-software-properties (for add-apt-repository).

diff --git a/src/vbox/renew-debian-changelog b/src/vbox/renew-debian-changelog
--- a/src/vbox/renew-debian-changelog
+++ b/src/vbox/renew-debian-changelog
@@ -1,4 +1,22 @@
 #!/bin/bash -e
+#
+# Debian Packaging Scripts
+# Copyright (C) 2002-2013 by Thomas Dreibholz
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Contact: dreibh@iem.uni-due.de
 
 . ./debian.conf
 
@@ -28,40 +46,55 @@ fi
 # ====== Revert debian/changelog and debian/control =========================
 rm -f LocalConfig.kmk
 if [ -e ".svn" ] ; then
-   # Revert Debian files
-   svn revert debian/changelog debian/control debian/rules debian/LocalConfig.kmk
    # Get SVN version identifier
    SVN_VERSION="`svnversion . | tr -d [M]`"
    BUILD_VERSION_IDENTIFIER="svn`printf "%07d" "${SVN_VERSION}"`${BUILD_SUFFIX}"
 else
    echo "*** Not an SVN repository ***"
-   # When running the first time, backup the original Debian files
-   if [ ! -e debian/changelog.orig ] ; then
-      cp debian/changelog debian/changelog.orig
-   fi
-   if [ ! -e debian/control.orig ] ; then
-      cp debian/control debian/control.orig
-   fi
-   if [ ! -e debian/rules.orig ] ; then
-      cp debian/rules debian/rules.orig
-   fi
-   if [ ! -e debian/LocalConfig.kmk.orig ] ; then
-      cp debian/LocalConfig.kmk debian/LocalConfig.kmk.orig
-   fi
-   # Revert Debian files (from the backup versions)
-   cp debian/changelog.orig debian/changelog
-   cp debian/control.orig debian/control
-   cp debian/rules.orig debian/rules
-   cp debian/LocalConfig.kmk.orig debian/LocalConfig.kmk
    # No special SVN version
    SVN_VERSION="0000000"
    BUILD_VERSION_IDENTIFIER="${BUILD_SUFFIX}"
 fi
+
+# When running the first time, backup the original Debian files
+BACKUP_FILES="changelog rules control virtualbox-source.files/control.modules.in virtualbox-guest-source.files/control.modules.in virtualbox-source.files/rules virtualbox-guest-source.files/rules"
+# VirtualBox has several control files ...
+for backupFile in $BACKUP_FILES ; do
+   if [ ! -e debian/${backupFile}.orig ] ; then
+      cp debian/${backupFile} debian/${backupFile}.orig
+   fi
+done
+# Revert Debian files (from the backup versions)
+for backupFile in $BACKUP_FILES ; do
+   cp debian/${backupFile}.orig debian/${backupFile}
+done
+
 echo -e "\x1b[34mBUILD_VERSION_IDENTIFIER: $BUILD_VERSION_IDENTIFIER\x1b[0m"
 
 
-# ====== Current SVN version ================================================
+# ====== Update changelog header from Config.kmk version ====================
+eval `grep "^VBOX_VERSION_MAJOR[ \t]*=[ \t]*" Config.kmk | sed -e "s/ //g"`
+eval `grep "^VBOX_VERSION_MINOR[ \t]*=[ \t]*" Config.kmk | sed -e "s/ //g"`
+eval `grep "^VBOX_VERSION_BUILD[ \t]*=[ \t]*" Config.kmk | sed -e "s/ //g"`
+
+if [ "$VBOX_VERSION_MAJOR" = "" ] ; then
+   echo >&2 "ERROR: Unable to extract VBOX_VERSION_MAJOR from Config.kmk!"
+   exit 1
+fi
+if [ "$VBOX_VERSION_MINOR" = "" ] ; then
+   echo >&2 "ERROR: Unable to extract VBOX_VERSION_MINOR from Config.kmk!"
+   exit 1
+fi
+if [ "$VBOX_VERSION_BUILD" = "" ] ; then
+   echo >&2 "ERROR: Unable to extract VBOX_VERSION_BUILD from Config.kmk!"
+   exit 1
+fi
+PLAIN_VERSION=${VBOX_VERSION_MAJOR}.${VBOX_VERSION_MINOR}.${VBOX_VERSION_BUILD}
+
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
+echo "Old CHANGELOG_HEADER=$CHANGELOG_HEADER"
+CHANGELOG_HEADER=`echo "$CHANGELOG_HEADER" | sed -e "s/^\([a-zA-Z0-9]*\) (\([0-9]*\.[0-9]*\.[0-9]*\)\(.*\))/\1 (${PLAIN_VERSION}\3)/g"`
+echo "New CHANGELOG_HEADER=$CHANGELOG_HEADER"
 
 # The package name, e.g. MyApplication
 PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
@@ -98,62 +131,123 @@ echo -e "\x1b[34m###############################################################
    echo ""
    echo "  * New Debian package from SVN revision ${SVN_VERSION}."
    echo ""
-   echo " -- $MAINTAINER  `env LANG=C date +"%a, %02d %b %Y %H:%M:%S %z"`"
+   echo " -- $MAINTAINER  `env LANG=en date +"%a, %02d %b %Y %H:%M:%S %z"`"
    echo ""
    sed <debian/changelog -e "s/^${PACKAGE} /${PACKAGE}${PACKAGE_SUFFIX} /g"
 ) >debian/changelog.new
 
 
-# ====== Change debian/control ==============================================
-conflicts=""
-for v in $VARIANTS ; do
-   if [ "$v" != "$VARIANT" ] ; then
-      if [ "$conflicts" = "" ] ; then
-         conflicts="$v"
-      else
-         conflicts="$conflicts,$v"
+# ====== Copy package files =================================================
+BUILD_PACKAGES=`grep "^Package: " debian/control.orig | sed -e "s/Package: //g"`
+cd debian
+echo "" >package-names.sed.tmp
+for buildPackage in $BUILD_PACKAGES ; do
+   buildPackageFiles=`find . -maxdepth 1 -name "${buildPackage}.*" -printf '%f\\n'`
+   echo "P=${buildPackage}" 
+   for buildPackageFile in $buildPackageFiles ; do
+      targetPackageFile=`echo "${buildPackageFile}" | sed -e "s/^${buildPackage}/${buildPackage}${PACKAGE_SUFFIX}/g"`
+      if [ "${buildPackageFile}" != "${targetPackageFile}" ] ; then
+         if [ -e "${targetPackageFile}" ] ; then
+            rm -rf "${targetPackageFile}"
+         fi
+         cp -a "${buildPackageFile}" "${targetPackageFile}"
       fi
+   done
+
+   conflicts=""
+   if [ "${PACKAGE_SUFFIX}" != "" ] ; then
+      conflicts="${buildPackage}"   # The original name
    fi
+   for v in $VARIANTS ; do
+      if [ "$v" != "$VARIANT" ] ; then
+         if [ "$conflicts" = "" ] ; then
+            conflicts="${buildPackage}-${v}"
+         else
+            conflicts="${conflicts}, ${buildPackage}-${v}"
+         fi
+      fi
+   done
+   
+   echo "s/^\(Package: ${buildPackage}\)$/Package: ${buildPackage}${PACKAGE_SUFFIX}\nConflicts: ${conflicts}\nReplaces: ${conflicts}/g" >>package-names.sed.tmp
+   echo "s/${buildPackage}$/${buildPackage}${PACKAGE_SUFFIX}/g" >>package-names.sed.tmp
+   echo "s/${buildPackage}[ \t]/${buildPackage}${PACKAGE_SUFFIX} /g" >>package-names.sed.tmp
 done
-(
-   # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-   # !!!! Using custom file debian/control.nornet as input !!!!
-   # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   
-   sed <debian/control.nornet \
-      -e "s/: ${PACKAGE}/: ${PACKAGE}${PACKAGE_SUFFIX}/g" \
-      -e "s/^Maintainer:.*/Maintainer: $MAINTAINER/g" \
-      -e "s/: Oracle VM /: Open Source /g" \
-      -e "s/^Package: ${PACKAGE}$/\0\nConflicts: ${conflicts}\nReplaces: ${conflicts}/g"
-) >debian/control.new
+sort <package-names.sed.tmp >package-names.sed
+rm -f package-names.sed.tmp
+cd ..
+
+
+# ====== Change debian/control ==============================================
+# VirtualBox has several control files ...
+CONTROL_FILES="control virtualbox-source${PACKAGE_SUFFIX}.files/control.modules.in virtualbox-guest-source${PACKAGE_SUFFIX}.files/control.modules.in"
+for controlFile in $CONTROL_FILES ; do
+   (
+      sed <debian/${controlFile} \
+         -f debian/package-names.sed \
+         -e "s/^Maintainer:.*/Maintainer: $MAINTAINER/g" \
+         -e "s/: Oracle VM /: Open Source /g" | \
+      sed -e "s/^Package: ${PACKAGE}${PACKAGE_SUFFIX}$/Package: ${PACKAGE}${PACKAGE_SUFFIX}\nProvides: ${PACKAGE}/g"
+         
+   ) >debian/${controlFile}.new
+done
 
 
 # ====== Change debian/rules ================================================
-(
-   sed <debian/rules \
-      -e "s/--disable-extpack/--disable-extpack --disable-kmods/g" \
-      -e "s/^#[ \t]*\(VNC=1[ \t]*\)/\1/g" \
-      -e "s/^#[ \t]*\(OSE=1[ \t]*\)/\1/g" \
-      -e "s/^\(verpkg[ \t]*\):=[ \t]*${PACKAGE}/\1:= ${PACKAGE}${PACKAGE_SUFFIX}/g"
-) >debian/rules.new
+RULES_FILES="rules virtualbox-source${PACKAGE_SUFFIX}.files/rules virtualbox-guest-source${PACKAGE_SUFFIX}.files/rules"
+for rulesFile in $RULES_FILES ; do
+   (
+      sed <debian/rules \
+         -e "s/^\(verpkg[ \t]*\):=[ \t]*${PACKAGE}/\1:= ${PACKAGE}${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(psource\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(gsource\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(pdkms\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(gdkms\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(sname\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(sxname\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(gname\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(uname\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/^\(uxname\):=\([a-zA-Z0-9+-]*\)$/\1 := \2${PACKAGE_SUFFIX}/g" \
+         -e "s/dh_strip --dbg-package=\$(sname)-dbg/dh_strip --dbg-package=${PACKAGE}-dbg${PACKAGE_SUFFIX}/g"
+   ) >debian/${rulesFile}.new
+done
 
 
-# ====== Change debian/LocalConfig.kmk ======================================
-(
-   cat debian/LocalConfig.kmk
-   echo ""
-   echo "VBOX_WITH_EXTPACK_VNC := 1"
-#    echo "VBOX_BUILD_PUBLISHER = ${BUILD_VERSION_IDENTIFIER}"
-) >debian/LocalConfig.kmk.new
+# ====== Change source install files ========================================
+if [ "${PACKAGE_SUFFIX}" != "" ] ; then
+   SOURCE_FILES="virtualbox-source${PACKAGE_SUFFIX}.links virtualbox-source${PACKAGE_SUFFIX}.install virtualbox-guest-source${PACKAGE_SUFFIX}.links virtualbox-guest-source${PACKAGE_SUFFIX}.install virtualbox-dkms${PACKAGE_SUFFIX}.dkms virtualbox-dkms${PACKAGE_SUFFIX}.links.in virtualbox-dkms${PACKAGE_SUFFIX}.install.in virtualbox-guest-dkms${PACKAGE_SUFFIX}.dkms virtualbox-guest-dkms${PACKAGE_SUFFIX}.links.in virtualbox-guest-dkms${PACKAGE_SUFFIX}.install.in"
+   for sourceFile in $SOURCE_FILES ; do
+      (
+         sed <debian/${sourceFile} \
+            -e "s/\/modules\/virtualbox\//\/modules\/virtualbox${PACKAGE_SUFFIX}\//g" \
+            -e "s/\/modules\/virtualbox$/\/modules\/virtualbox${PACKAGE_SUFFIX}/g" \
+            -e "s/\/modules\/virtualbox-guest\//\/modules\/virtualbox-guest${PACKAGE_SUFFIX}\//g" \
+            -e "s/\/modules\/virtualbox-guest$/\/modules\/virtualbox-guest${PACKAGE_SUFFIX}/g" \
+            -e "s/^PACKAGE_NAME=\"virtualbox\"$/PACKAGE_NAME=\"virtualbox${PACKAGE_SUFFIX}\"/g" \
+            -e "s/^PACKAGE_NAME=\"virtualbox-guest\"$/PACKAGE_NAME=\"virtualbox-guest${PACKAGE_SUFFIX}\"/g" \
+            -e "s/virtualbox-guest-CVERSION/virtualbox-guest${PACKAGE_SUFFIX}-CVERSION/g" \
+            -e "s/virtualbox-CVERSION/virtualbox${PACKAGE_SUFFIX}-CVERSION/g"
+      ) >debian/${sourceFile}.new
+   done
+fi
+
+
+# # ====== Change debian/LocalConfig.kmk ======================================
+# (
+#    cat debian/LocalConfig.kmk
+#    echo ""
+# #    echo "VBOX_WITH_EXTPACK_VNC := 1"
+# #    echo "VBOX_BUILD_PUBLISHER = ${BUILD_VERSION_IDENTIFIER}"
+# ) >debian/LocalConfig.kmk.new
+
 
 # ====== Write LocalConfig.kmk ==============================================
 (
-   echo ""
+   # echo "VBOX_WITH_EXTPACK_VNC := 1"
    echo "VBOX_BUILD_PUBLISHER = ${BUILD_VERSION_IDENTIFIER}"
 ) >LocalConfig.kmk
 
 
 # ====== Apply changes ======================================================
-mv debian/changelog.new       debian/changelog
-mv debian/control.new         debian/control
-mv debian/rules.new           debian/rules
-mv debian/LocalConfig.kmk.new debian/LocalConfig.kmk
+for updatedFile in changelog $CONTROL_FILES $RULES_FILES $SOURCE_FILES ; do
+   mv "debian/${updatedFile}.new" "debian/${updatedFile}"
+done
