Added KVM support to Check-VSystem script.

diff --git a/src/Check-VSystem b/src/Check-VSystem
--- a/src/Check-VSystem
+++ b/src/Check-VSystem
@@ -1,7 +1,9 @@
 #!/bin/bash -e
 #
 # Check status of virtual system
-# Copyright (C) 2013 by Thomas Dreibholz
+# Copyright (C) 2013-2015 by Thomas Dreibholz
+# Copyright (C) 2014 by Forough Golkar <forough.golkar87@gmail.com>
+# Copyright (C) 2013 by Nima Fallah Darya <nima.darya@gmail.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -51,7 +53,20 @@ fi
 
 # ====== Obtain machine status ==============================================
 status="BAD_MACHINE"
-s=`vminfo "$MACHINE_NAME" --machinereadable | grep VMState=` && \
-status=`echo $s | sed -e "s/VMState=//" -e "s/\"//g"` || true
+
+if [ "$NorNet_Server_VirtualizationSystem" = "" -o "$NorNet_Server_VirtualizationSystem" = "VirtualBox" ] ; then
+   s=`vminfo "$MACHINE_NAME" --machinereadable | grep VMState=` && \
+   status=`echo $s | sed -e "s/VMState=//" -e "s/\"//g"` || true
+
+elif [ "$NorNet_Server_VirtualizationSystem" = "KVM" ] ; then
+    status=`sudo -u $NorNet_LocalNode_NorNetUser env LANG=C HOME=~$NorNet_LocalNode_NorNetUser virsh dominfo "$MACHINE_NAME" | grep "^State:" | sed -e "s/State://" -e "s/^ *//g" -e "s/ *$//g"` || true
+    if [ "$status" = "shut off" ] ; then
+       status="poweroff"
+    fi
+
+else
+   echo >&2 "ERROR: Bad setting $NorNet_Server_VirtualizationSystem for NorNet_Server_VirtualizationSystem!"
+   exit 1
+fi
 
 echo "$status"
