Add source address to route configuration.

diff --git a/src/Interface-Setup b/src/Interface-Setup
--- a/src/Interface-Setup
+++ b/src/Interface-Setup
@@ -128,10 +128,11 @@ elif [ "$state" = "up" ] ; then
          gateway="$3"
          metric="$4"
          options="$5"
+         source=`echo "$1" | sed -e "s/\/[0-9]*$//g"`
          shift ; shift ; shift ; shift ; shift
-         /bin/echo "Adding $address, route to $network via $gateway with metric $metric ..."
+         /bin/echo "Adding $address, route to $network src $source via $gateway with metric $metric ..."
          /sbin/ip addr add "$address" dev "$interface" $options || /bin/echo "ERROR: Failed to add address" || true
-         /sbin/ip route add "$network" via "$gateway" dev "$interface" metric "$metric" || /bin/echo "ERROR: Failed to add route" || true
+         /sbin/ip route add "$network" via "$gateway" dev "$interface" src "$source" metric "$metric" || /bin/echo "ERROR: Failed to add route" || true
       done
 
    ) >>$logFile 2>&1
