Improved script.

diff --git a/src/IPsec-Setup b/src/IPsec-Setup
--- a/src/IPsec-Setup
+++ b/src/IPsec-Setup
@@ -48,6 +48,26 @@ create-sa ()
    local auth_key="$5"
    # !!! local esp_parameters="-E null -A null"   # !!! Just for testing! !!!
    local esp_parameters="-E aes-ctr \"${crypt_key}\" -A hmac-sha512 \"${auth_key}\""
+   if [ "$id" == "" ] ; then
+      echo >&2 "ERROR: id not specified!"
+      exit 1
+   fi
+   if [ "$localAddress" == "" ] ; then
+      echo >&2 "ERROR: localAddress not specified!"
+      exit 1
+   fi
+   if [ "$remoteAddress" == "" ] ; then
+      echo >&2 "ERROR: remoteAddress not specified!"
+      exit 1
+   fi
+   if [ "$crypt_key" == "" ] ; then
+      echo >&2 "ERROR: crypt_key not specified!"
+      exit 1
+   fi
+   if [ "$auth_key" == "" ] ; then
+      echo >&2 "ERROR: auth_key not specified!"
+      exit 1
+   fi
 
    # ====== The outgoing ID on one side is the incoming ID on the other! ====
    if [[ "${localAddress}" < "${remoteAddress}" ]] ; then
@@ -55,13 +75,11 @@ create-sa ()
       local id2=2
       local id3=3
       local id4=4
-      echo "X-1"
    else
       local id1=2
       local id2=1
       local id3=4
       local id4=3
-      echo "X-2"
    fi
 
    # ====== Configure IPsec =================================================
@@ -80,23 +98,49 @@ EOF
 }
 
 
+# ====== Configuration ======================================================
+bridgeInterface=br0
+physicalInterface=eth0
+
+
 if [ "$1" == "on" ] ; then
    flush
 
    # ====== Example =========================================================
-   localAddress="158.36.99.74"  ; remoteAddress="128.39.37.186"
-   # localAddress="128.39.37.186" ; remoteAddress="158.36.99.74"
+   id=""
+   localAddress=""
+   remoteAddress=""
+   crypt_key=""
+   auth_key=""
 
+   . /root/nornet-vpn.conf
+
+   # ====== Configure bridge ================================================
+   brctl addbr $bridgeInterface || true
+   brctl addif $bridgeInterface $physicalInterface || true
+   ip link set $bridgeInterface up
+
+   # ====== Configure IPsec =================================================
    # 36 bytes for encryption key parameter
    # Encryption: 36 characters (32 + 4 IV)
    # Auth:       64 characters
-   create-sa 001   ${localAddress} ${remoteAddress} \
-      "wEQoA5ak7iw5dH2t4J63lmFhdZjMAhVkbGby" \
-      "SB9emJJt5Kne7BJmBleCOjrj0UYNKxr9ccRmfnPlmwAPBuamtZnitnogcDUtDAcO"
+   create-sa ${id} ${localAddress} ${remoteAddress} ${crypt_key} ${auth_key}
+
+   # ====== Configure tunnel ================================================
+   ip link del tunnel${id} 2>/dev/null || true
+   ip link add tunnel${id} type gretap remote ${remoteAddress} local ${localAddress} ttl 255
+   brctl addif $bridgeInterface tunnel${id}
+   # ip addr add 192.168.255.2/24 dev tunnel${id}
+   ip link set tunnel${id} up
 
    show
 
 elif [ "$1" == "off" ] ; then
+   ip link set $bridgeInterface down || true
+   brctl delbr $bridgeInterface || true
+
+   ip link del tunnel001 || true
+
    flush
 elif [ "$1" == "show" ] ; then
    show
