Updated Make-Research-VM with KVM support.

diff --git a/src/Make-Research-VM b/src/Make-Research-VM
--- a/src/Make-Research-VM
+++ b/src/Make-Research-VM
@@ -1,7 +1,8 @@
 #!/bin/bash -e
 #
 # Make Research VM
-# Copyright (C) 2012-2013 by Thomas Dreibholz
+# Copyright (C) 2012-2015 by Thomas Dreibholz <dreibh@simula.no>
+# Copyright (C) 2014 by Forough Golkar <forough.golkar87@gmail.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,10 +21,20 @@
 
 
 if [ $# -lt 4 ] ; then
-   echo >&2 "Usage: $0 VM_name ISO_name memory_MiB disk_GiB [Fixed|Standard]"
+   echo >&2 "Usage: $0 VM_name ISO_name memory_MiB disk_GiB [fixed|standard]"
    exit 1
 fi
 
+NORNET_DIRECTORY="/etc/nornet"
+
+# ====== Get NorNet parameters ==============================================
+if [ -e $NORNET_DIRECTORY/nornetapi-config ] ; then
+   . $NORNET_DIRECTORY/nornetapi-config
+elif [ -e ./nornetapi-config ] ; then
+   . ./nornetapi-config
+fi
+
+# ====== Get command-line parameters ========================================
 VM_NAME="$1"
 ISO_NAME="$2"
 if [ ! -e "$ISO_NAME" ] ; then
@@ -34,27 +45,70 @@ let MEMORY_SIZE=1*$3
 let DISK_SIZE=1024*$4
 VARIANT="$5"
 if [ "$VARIANT" = "" ] ; then
-   VARIANT="Fixed"
+   VARIANT="fixed"
+elif [ "$VARIANT" = "fixed" -o "$VARIANT" = "Fixed" ] ; then
+   VARIANT="fixed"
+elif [ "$VARIANT" = "standard" -o "$VARIANT" = "Standard" ] ; then
+   VARIANT="standard"
+else
+   echo >&2 "ERROR: Bad disk variant $VARIANT!"
+   exit 1
 fi
 
 CPUS="1"
 VRAM="16"
 
 
-VBoxManage unregistervm "$VM_NAME" --delete || true
+if [ "$NorNet_Server_VirtualizationSystem" = "" -o "$NorNet_Server_VirtualizationSystem" = "VirtualBox" ] ; then
+   VBoxManage unregistervm "$VM_NAME" --delete || true
 
-VBoxManage createvm --register --name "$VM_NAME" --ostype Fedora_64
-VBoxManage modifyvm "$VM_NAME" --cpus "$CPUS" \
-                               --memory "$MEMORY_SIZE" --vram "$VRAM" \
-                               --rtcuseutc on --firmware bios --chipset piix3 --acpi on --ioapic on \
-                               --hwvirtex on --pae on --boot1 dvd --boot2 disk --boot3 none --boot4 none
-VBoxManage modifyvm "$VM_NAME" --nic1 bridged --nictype1 virtio --bridgeadapter1 eth0 --cableconnected1 on --macaddress1 auto --nicpromisc1 allow-all
-VBoxManage storagectl "$VM_NAME" --name "SCSI Controller" --add scsi --controller LSILogic
-VBoxManage storageattach "$VM_NAME" --storagectl "SCSI Controller" --port 0 --device 0 --type dvddrive \
-                                    --medium "$ISO_NAME"
-VBoxManage createhd --filename "$HOME/VirtualBox VMs/$VM_NAME/DH0.vdi" --size "$DISK_SIZE" --format vdi --variant "$VARIANT"
-VBoxManage storageattach "$VM_NAME" --storagectl "SCSI Controller" --port 1 --device 0 --type hdd \
-                                    --medium "$HOME/VirtualBox VMs/$VM_NAME/DH0.vdi"
+   VBoxManage createvm --register --name "$VM_NAME" --ostype Fedora_64
+   VBoxManage modifyvm "$VM_NAME" --cpus "$CPUS" \
+                                 --memory "$MEMORY_SIZE" --vram "$VRAM" \
+                                 --rtcuseutc on --firmware bios --chipset piix3 --acpi on --ioapic on \
+                                 --hwvirtex on --pae on --boot1 dvd --boot2 disk --boot3 none --boot4 none
+   VBoxManage modifyvm "$VM_NAME" --nic1 bridged --nictype1 virtio --bridgeadapter1 eth0 \
+                                  --cableconnected1 on --macaddress1 auto --nicpromisc1 allow-all
+   VBoxManage storagectl "$VM_NAME" --name "SCSI Controller" --add scsi --controller LSILogic
+   VBoxManage storageattach "$VM_NAME" --storagectl "SCSI Controller" --port 0 --device 0 --type dvddrive \
+                                       --medium "$ISO_NAME"
+   vboxVariant="Standard"
+   if [ "$VARIANT" = "fixed" ] ; then
+      vboxVariant="Fixed"
+   fi
+   VBoxManage createhd --filename "$HOME/VirtualBox VMs/$VM_NAME/DH0.vdi" --size "$DISK_SIZE" --format vdi \
+                                                                          --variant "$VARIANT"
+   VBoxManage storageattach "$VM_NAME" --storagectl "SCSI Controller" --port 1 --device 0 --type hdd \
+                                       --medium "$HOME/VirtualBox VMs/$VM_NAME/DH0.vdi"
+
+elif [ "$NorNet_Server_VirtualizationSystem" = "KVM" ] ; then
+   let DISK_SIZE=$4
+   if [ ! -d "$HOME/KVM/$VM_NAME" ]; then
+      sudo -u $NorNet_LocalNode_NorNetUser mkdir -p "$HOME/KVM/$VM_NAME"
+   fi
+
+   sparseMode="true"
+   if [ "$VARIANT" = "fixed" ] ; then
+      sparseMode="false"
+   fi
+
+   virt-install --connect qemu:///system  --virt-type "kvm"\
+                --name "$VM_NAME" \
+                --os-type="linux" --os-variant="fedora18" \
+                --vcpu="$CPUS" \
+                --ram "$MEMORY_SIZE" \
+                --disk path="$HOME/KVM/$VM_NAME/DH0.img,size="$DISK_SIZE",device=disk,bus=scsi",sparse=$sparseMode \
+                --graphics vnc \
+                --network bridge:br0 \
+                --cdrom "$ISO_NAME" \
+                --boot cdrom,hd \
+                --noautoconsole
+
+else
+   echo >&2 "ERROR: Bad setting $NorNet_Server_VirtualizationSystem for NorNet_Server_VirtualizationSystem!"
+   exit 1
+fi
+
 
 (
    echo "NAME=\"$VM_NAME"\"
