Some improvements.

diff --git a/src/Routing-Setup b/src/Routing-Setup
--- a/src/Routing-Setup
+++ b/src/Routing-Setup
@@ -345,10 +345,15 @@ checkProviders () {
    local selectedProviders="$2"
    local oldIFS=$IFS
    IFS=","
-   for provider in $selectedProviders ; do
-      echo "p=$provider"
-      if [[ ! $availableProviders =~ ^$|^$provider$|^$provider,|,$provider,|,$provider$ ]] ; then
-         echo >&2 "ERROR: Provider \"$provider\" is not in the list of available providers \"$availableProviders\"!"
+   for b in $selectedProviders ; do
+      found=0
+      for a in $availableProviders ; do
+         if [ "$a" == "$b" ] ; then
+            found=1
+         fi
+      done
+      if [ $found -eq 0 ] ; then
+         echo >&2 "ERROR: Provider \"$b\" is not in the list of available providers \"$availableProviders\"!"
          exit 1
       fi
    done
