Added per-provider configuration option for tunnelbox.

diff --git a/src/Routing-Setup b/src/Routing-Setup
--- a/src/Routing-Setup
+++ b/src/Routing-Setup
@@ -337,3 +337,20 @@ remove-nat ()
       done
    fi
 }
+
+
+# ###### Check whether a provider is in a list of available providers #######
+checkProviders () {
+   local availableProviders="$1"
+   local selectedProviders="$2"
+   local oldIFS=$IFS
+   IFS=","
+   for provider in $selectedProviders ; do
+      echo "p=$provider"
+      if [[ ! $availableProviders =~ ^$|^$provider$|^$provider,|,$provider,|,$provider$ ]] ; then
+         echo >&2 "ERROR: Provider \"$provider\" is not in the list of available providers \"$availableProviders\"!"
+         exit 1
+      fi
+   done
+   IFS=$oldIFS
+}
diff --git a/src/Tunnelbox-Setup b/src/Tunnelbox-Setup
--- a/src/Tunnelbox-Setup
+++ b/src/Tunnelbox-Setup
@@ -20,15 +20,15 @@
 #
 
 
+# ###### Main program #######################################################
 state="$1"
-bootstrap="$2"
+shift
 
 if [ "$state" != "start" -a "$state" != "stop" -a \
      "$state" != "restart" -a "$state" != "status" -a "$state" != "reset" -a "$state" != "coldstart" ] ; then
-   echo >&2 "Usage: $0 start|stop|status|reset|coldstart [-bootstrap]"
+   echo >&2 "Usage: $0 start|stop|status|reset|coldstart [-providers list_of_providers] [-bootstrap]"
    exit 1
 fi
-
 
 WORK_DIRECTORY="."
 if [ ! -e "$WORK_DIRECTORY/Routing-Setup" ] ; then
@@ -57,17 +57,27 @@ fi
 
 
 success=1
-if [ "$bootstrap" = "-bootstrap" ] ; then
-    log "Entering BOOTSTRAP ..."
-    . ./tunnelbox-bootstrap || success=0
-    log-action "Finished BOOTSTRAP ..."
-else
-    log "Entering Tunnelbox setup ..."
-    success=1
-    . ./tunnelbox-config || success=0
-    log-action "Finished Tunnelbox setup ..."
-    log-result $success
-fi
+selectedProviders=""
+while [ "$1" != "" ] ; do
+   if [ "$1" = "-bootstrap" ] ; then
+       log "Entering BOOTSTRAP ..."
+       . ./tunnelbox-bootstrap || success=0
+       log-action "Finished BOOTSTRAP ..."
+   elif [ "$1" = "-providers" ] ; then
+      selectedProviders="$2"
+      shift
+   else
+      echo >&2 "ERROR: Bad argument $1"
+      exit 1
+   fi
+   shift
+done
+
+
+log "Entering Tunnelbox setup ..."
+success=1
+. ./tunnelbox-config || success=0
+log-action "Finished Tunnelbox setup ..."
 
 log-result $success
 if [ $success -eq 0 ] ; then
diff --git a/src/t2 b/src/t2
--- a/src/t2
+++ b/src/t2
@@ -3,7 +3,7 @@
 providers="dfn,telekom"
 
 for provider in dfn telenor uninett telekom ; do
-   if [[ $providers =~ ^$|^$provider$|^$provider,|,$provider,|,$provider$ ]] ; then
+   if [[ "$providers" =~ ^$|^$provider$|^$provider,|,$provider,|,$provider$ ]] ; then
       echo "p=$provider"
 
    else
@@ -11,3 +11,27 @@ for provider in dfn telenor uninett telekom ; do
    fi
 done
 
+
+echo "-----"
+
+
+availableProviders="dfn,telekom,tele2"
+selectedProviders="dfn,telekom,uninett"
+
+
+checkProviders () {
+   local availableProviders="$1"
+   local selectedProviders="$2"
+   local oldIFS=$IFS
+   IFS=","
+   for provider in $selectedProviders ; do
+      echo "p=$provider"
+      if [[ ! "$availableProviders" =~ ^$|^$provider$|^$provider,|,$provider,|,$provider$ ]] ; then
+         echo >&2 "ERROR: Provider \"$provider\" is not in the list of available providers \"$availableProviders\"!"
+         exit 1
+      fi
+   done
+   IFS=$oldIFS
+}
+
+checkProviders "$availableProviders" "$selectedProviders"
