Some more Server configuration improvements.

diff --git a/src/Server-Setup b/src/Server-Setup
--- a/src/Server-Setup
+++ b/src/Server-Setup
@@ -20,9 +20,50 @@
 
 
 # ###### Get existing interface configuration (if available) ################
+MAY_BE_CONTROLBOX=0
 parse-interface-configuration ()
 {
-   return 1
+   local inputFile="$1"
+   local interface="$2"
+
+   local found=0
+   local writeMode=0
+   while read inputLine ; do      
+      if [[ $inputLine =~ ^auto([ \t]*)${interface}(:[0-9]*|)([ \t]*)(.*)$ ]] ; then
+         echo "$inputLine"
+         found=1
+      else
+         # ====== New interface? =========================================
+         if [[ $inputLine =~ ^iface([ \t]*)|^([ \t]*)$ ]] ; then
+            if [[ $inputLine =~ ^iface([ \t]*)${interface}(:[0-9]*|)([ \t]*)(.*)$ ]] ; then
+               writeMode=1
+               echo "$inputLine"
+            else
+               if [ $writeMode -eq 1 ] ; then
+                  echo ""
+                  writeMode=0
+               fi
+            fi
+            
+         # ====== Write interface configuration ==========================
+         elif [ $writeMode -eq 1 ] ; then
+            if [[ $inputLine =~ ^([ \t]*)metric([ \t]*)([0-9]*)([ \t]*)(.*)$ ]] ; then
+               metric=${BASH_REMATCH[3]}
+               if [ "$metric" -le 5 ] ; then
+                  # Non-NorNet metric (< default provider) => may be control box!
+                  result=2
+                  MAY_BE_CONTROLBOX=1
+               fi
+            elif [[ $inputLine =~ ^([ \t]*)gateway([ \t]*)([0-9]*)([ \t]*)(.*)$ ]] ; then
+               # Interface has a gateway => may be control box!
+               MAY_BE_CONTROLBOX=1
+            fi
+            echo "   $inputLine"
+         fi
+      fi
+   done <$inputFile
+
+   return $found
 }
 
 
@@ -35,7 +76,7 @@ if [ $# -lt 8 -o \
      "$3" != "-site" -o \
      "$5" != "-interface" -o \
      "$7" != "-providers" ] ; then
-   echo >&2 "Usage: $0 FQDN node_index -site site_index -interface interface_name -providers default_provider [provider2] ..."
+   echo >&2 "Usage: $0 FQDN node_index -site site_index -interface interface_name -providers default_provider[,provider2,...] [-controlbox]"
    if [ -e "$LAST_PARAMETERS_FILE" ] ; then
       LAST_PARAMETERS_ARGS=`cat $LAST_PARAMETERS_FILE`
       echo -en "\x1b[33mRun $0 $LAST_PARAMETERS_ARGS? [yes/no]?\x1b[0m "
@@ -54,20 +95,23 @@ FQDN="$1"
 NodeIndex="$2"
 SiteIndex="$4"
 InterfaceName="$6"
-shift ; shift ; shift ; shift ; shift ; shift ; shift
-ProviderList="$@"
+ProviderList="$8"
+ControlBoxMode="$9"
+if [ "$ControlBoxMode" != "" -a "$ControlBoxMode" != "-controlbox" ] ; then
+   echo >&2 "ERROR: Bad control box mode! Do you mean -controlbox?"
+   exit 1
+fi
 
 # ====== Create network configuration =======================================
 echo "???????"
-./Make-Server-Configuration "$FQDN" "$NodeIndex" -site "$SiteIndex" -interface "$InterfaceName" -providers "$ProviderList" || exit 1
+./Make-Server-Configuration "$FQDN" "$NodeIndex" -site "$SiteIndex" -interface "$InterfaceName" -providers "$ProviderList" $ControlBoxMode || exit 1
 AllEthernetInterfaces=`ip link show | awk '/^([0-9]*:) ([a-zA-Z0-9\-]+):/ { print $2 }' | grep "^eth" | sed -e "s/:$//" | xargs`
-echo "A=$AllEthernetInterfaces"
 for interface in $AllEthernetInterfaces ; do
-   echo "I=$interface"
    if [ "$interface" != "lo" -a "$interface" != "$InterfaceName" ] ; then
       (
-         if ! parse-interface-configuration $interface /etc/network/interfaces ; then
-            echo -e "\nauto $interface"
+         echo -e "\n# ====== Additional interface $interface ======"
+         if parse-interface-configuration /etc/network/interfaces $interface  ; then
+            echo -e "auto $interface"
             echo -e "iface $interface inet static"
             echo -e "   address 0.0.0.0"
             echo -e "   netmask 0.0.0.0"
@@ -76,8 +120,17 @@ for interface in $AllEthernetInterfaces ; do
    fi
 done
 
-echo "STOP"
-exit 1
+if [ "$MAY_BE_CONTROLBOX" != "" ] ; then
+   if [ "$ControlBoxMode" != "-controlbox" ] ; then
+      echo -e  "\n\x1b[31mWARNING: Node has non-NorNet interface with gateway or small metric!\x1b[0m"
+      echo -en "\x1b[31mWARNING: Are you really sure that this node is NOT a Control Box? [yes/no]\x1b[0m? "
+      read -er applyChanges
+      if [ "$applyChanges" != "yes" -a "$applyChanges" != "y" ] ; then
+         exit 1
+      fi
+   fi
+fi
+
 
 # ====== Create other configurations ========================================
 ( cat /etc/modules | grep -v "^dummy" ; echo "dummy numdummies=10" ) >modules.new
