Added bridge configuration option.

diff --git a/src/Server-Setup b/src/Server-Setup
--- a/src/Server-Setup
+++ b/src/Server-Setup
@@ -77,7 +77,7 @@ if [ $# -lt 8 -o \
      "$3" != "-site" -o \
      "$5" != "-interface" -o \
      "$7" != "-providers" ] ; then
-   echo >&2 "Usage: $0 FQDN node_index -site site_index -interface interface_name -providers default_provider[,provider2,...] [-controlbox]"
+   echo >&2 "Usage: $0 FQDN node_index -site site_index -interface interface_name -providers default_provider[,provider2,...] [-controlbox] [-bridge interface_name]"
    if [ -e "$LAST_PARAMETERS_FILE" ] ; then
       LAST_PARAMETERS_ARGS=`cat $LAST_PARAMETERS_FILE`
       echo -en "\x1b[33mRun $0 $LAST_PARAMETERS_ARGS? [yes/no]?\x1b[0m "
@@ -109,11 +109,19 @@ SiteIndex="$4"
 InterfaceName="$6"
 ProviderList="$8"
 ControlBoxMode=""
+BridgeInterface=""
 MakeServerConfigurationPath=""
 shift ; shift ; shift ; shift ; shift ; shift ; shift ; shift
 while [ $# -gt 0 ] ; do
    if [ "$1" = "-controlbox" ] ; then
       ControlBoxMode="-controlbox"
+   elif [ "$1" = "-bridge" ] ; then
+      BridgeInterface="$2"
+      if [ "$BridgeInterface" == "" ] ; then
+         echo >&2 "ERROR: No bridge interface given!"
+         exit 1
+      fi
+      shift
    elif [ "$1" = "-from-current-dir" ] ; then
       MakeServerConfigurationPath="`pwd`/"
       echo "NOTE: Running Make-Server-Configuration from $MakeServerConfigurationPath!"
