Some grub handling fixes.

diff --git a/src/System-Maintenance b/src/System-Maintenance
--- a/src/System-Maintenance
+++ b/src/System-Maintenance
@@ -254,12 +254,22 @@ fi
 
 # ====== Fix bootloader =====================================================
 if [ $DONT_TOUCH_GRUB -eq 0 ] ; then
-   if [ "$Variant" != "FreeBSD" ] ; then
+   if [ "$Variant" == "Ubuntu" -o "$Variant" == "Debian" ] ; then
       echo -e "\x1b[34m`date +%FT%H:%M:%S`: Ensuring that Grub configuration is up-to-date ...\x1b[0m"
       sudo nohup </dev/null grub-install /dev/sda >/tmp/install.log 2>&1 || true
-      if ! sudo nohup update-grub sudo nohup </dev/null grub-install /dev/sda >>/tmp/install.log 2>&1 ; then
+      if ! sudo nohup </dev/null update-grub >>/tmp/install.log 2>&1 ; then
          cat /tmp/install.log
          echo >&2 "ERROR: Something went wrong with update-grub!"
+         exit 1
+      fi
+      cat /tmp/install.log
+   elif [ "$Variant" == "Fedora" ] ; then
+      echo -e "\x1b[34m`date +%FT%H:%M:%S`: Ensuring that Grub configuration is up-to-date ...\x1b[0m"
+      sudo nohup </dev/null grub2-mkconfig -o "$(readlink -e /etc/grub2.cfg)" >/tmp/install.log 2>&1 || true
+      if ! sudo nohup </dev/null grub2-install /dev/sda >>/tmp/install.log 2>&1 ; then
+         cat /tmp/install.log
+         echo >&2 "ERROR: Something went wrong with grub2-install!"
+         cat /tmp/install.log
          exit 1
       fi
       cat /tmp/install.log
