Added FreeBSD support in System-Maintenance script

diff --git a/src/System-Maintenance b/src/System-Maintenance
--- a/src/System-Maintenance
+++ b/src/System-Maintenance
@@ -1,7 +1,7 @@
 #!/bin/bash -e
 #
 # System Maintenance
-# Copyright (C) 2013 by Thomas Dreibholz
+# Copyright (C) 2013-2015 by Thomas Dreibholz
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -44,6 +44,8 @@ if [ -e /etc/network/interfaces ] ; then
    Variant="Debian"
 elif [ -e /etc/sysconfig/network ] ; then
    Variant="Fedora"
+elif [ -e /etc/freebsd-update.conf ] ; then
+   Variant="FreeBSD"
 else
    echo >&2 "ERROR: Unknown/unsupported operating system? Cannot determine how to configure network!"
    exit 1
@@ -67,6 +69,13 @@ fi
 if [ "$Variant" = "Debian" ] ; then
    echo -e "\x1b[34m`date +%FT%H:%M:%S`: Updating package repositories ...\x1b[0m"
    sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
+elif [ "$Variant" = "FreeBSD" ] ; then
+   echo -e "\x1b[34m`date +%FT%H:%M:%S`: Updating package repositories ...\x1b[0m"
+   sudo freebsd-update fetch
+   sudo pkg update
+   if [ -e /usr/sbin/portsnap ] ; then
+      sudo portsnap fetch
+   fi
 fi
    
 # ====== apt-get package fixes ==============================================
@@ -85,6 +94,10 @@ if [ "$Variant" = "Debian" ] ; then
    cat /tmp/install.log
 elif [ "$Variant" = "Fedora" ] ; then
    ( sudo yum clean all && sudo yum upgrade -y ) >/tmp/install.log 2>&1 &
+   wait
+   cat /tmp/install.log
+elif [ "$Variant" = "FreeBSD" ] ; then
+   ( sudo freebsd-update install ; sudo pkg upgrade -y ; if [ -e /usr/sbin/portsnap ] ; then sudo portsnap update ; fi ) >/tmp/install.log 2>&1 &
    wait
    cat /tmp/install.log
 fi
@@ -198,14 +211,16 @@ fi
 
 # ====== Fix bootloader =====================================================
 if [ $DONT_TOUCH_GRUB -eq 0 ] ; then
-   echo -e "\x1b[34m`date +%FT%H:%M:%S`: Ensuring that Grub configuration is up-to-date ...\x1b[0m"
-   sudo nohup </dev/null grub-install /dev/sda >/tmp/install.log 2>&1 || true
-   if ! sudo nohup update-grub sudo nohup </dev/null grub-install /dev/sda >>/tmp/install.log 2>&1 ; then
+   if [ "$Variant" != "FreeBSD" ] ; then
+      echo -e "\x1b[34m`date +%FT%H:%M:%S`: Ensuring that Grub configuration is up-to-date ...\x1b[0m"
+      sudo nohup </dev/null grub-install /dev/sda >/tmp/install.log 2>&1 || true
+      if ! sudo nohup update-grub sudo nohup </dev/null grub-install /dev/sda >>/tmp/install.log 2>&1 ; then
+         cat /tmp/install.log
+         echo >&2 "ERROR: Something went wrong with update-grub!"
+         exit 1
+      fi
       cat /tmp/install.log
-      echo >&2 "ERROR: Something went wrong with update-grub!"
-      exit 1
    fi
-   cat /tmp/install.log
 fi
    
 # ====== apt-file cache update ==============================================
@@ -216,7 +231,11 @@ if [ "$Variant" = "Debian" ] ; then
       sudo /usr/bin/apt-file update >/dev/null
    fi
 fi
-sudo updatedb
+if [ "$Variant" != "FreeBSD" ] ; then
+   sudo updatedb
+else
+   sudo -u nobody /usr/libexec/locate.updatedb
+fi
 
 # ====== Delete /etc/udev/rules.d/70-persistent-net.rules ===================
 if [ "$Variant" = "Debian" ] ; then
